# Generated by Django 5.1 on 2024-08-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='livro',
            name='imagem',
            field=models.ImageField(default='imagens/default.jpg', upload_to='imagens/'),
        ),
    ]
