# Generated by Django 5.1.1 on 2024-12-20 10:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('core', '0002_estantelivro'), ('core', '0003_historicoatividade'), ('core', '0004_customuser_profile_image_alter_customuser_groups_and_more'), ('core', '0005_alter_estantelivro_options_estantelivro_categoria_and_more'), ('core', '0006_livro_classificacao'), ('core', '0007_estantelivro_classificacao')]

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=50)),
                ('livro_id', models.CharField(max_length=100)),
                ('titulo_livro', models.CharField(max_length=255)),
                ('detalhes', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Atividade',
                'verbose_name_plural': 'Histórico de Atividades',
                'ordering': ['-data'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/', verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='customuser_set', related_query_name='customuser', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_set', related_query_name='customuser', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='livro',
            name='classificacao',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, 'A classificação deve ser de pelo menos 1 estrela'), django.core.validators.MaxValueValidator(5, 'A classificação não pode ser maior que 5 estrelas')], verbose_name='Classificação'),
        ),
        migrations.CreateModel(
            name='EstanteLivro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livro_id', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(choices=[('favorito', 'Favorito'), ('lendo', 'Lendo'), ('vou_ler', 'Vou ler'), ('lido', 'Lido')], max_length=20)),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('capa', models.URLField(blank=True)),
                ('data_lancamento', models.CharField(blank=True, max_length=50)),
                ('sinopse', models.TextField(blank=True)),
                ('data_adicao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('editora', models.CharField(blank=True, max_length=255)),
                ('idioma', models.CharField(blank=True, max_length=50)),
                ('isbn', models.CharField(blank=True, max_length=13)),
                ('manual', models.BooleanField(default=False)),
                ('notas_pessoais', models.TextField(blank=True)),
                ('numero_paginas', models.IntegerField(blank=True, null=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('classificacao', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, 'A classificação deve ser de pelo menos 1 estrela'), django.core.validators.MaxValueValidator(5, 'A classificação não pode ser maior que 5 estrelas')], verbose_name='Classificação')),
            ],
            options={
                'ordering': ['titulo'],
                'verbose_name': 'Livro na Estante',
                'verbose_name_plural': 'Livros na Estante',
                'unique_together': {('usuario', 'livro_id', 'tipo')},
            },
        ),
    ]
