# Generated by Django 5.1 on 2024-11-27 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_estantelivro'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=50)),
                ('livro_id', models.CharField(max_length=100)),
                ('titulo_livro', models.CharField(max_length=255)),
                ('detalhes', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Atividade',
                'verbose_name_plural': 'Histórico de Atividades',
                'ordering': ['-data'],
            },
        ),
    ]
