# Generated by Django 5.1 on 2024-09-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cadastro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100)),
                ('assunto', models.CharField(max_length=255)),
                ('mensagem', models.TextField()),
                ('data', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Cadastro',
        ),
    ]
