# Generated by Django 5.1.1 on 2024-11-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customuser_profile_image_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estantelivro',
            options={'ordering': ['titulo'], 'verbose_name': 'Livro na Estante', 'verbose_name_plural': 'Livros na Estante'},
        ),
        migrations.AddField(
            model_name='estantelivro',
            name='categoria',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='estantelivro',
            name='editora',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='estantelivro',
            name='idioma',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='estantelivro',
            name='isbn',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AddField(
            model_name='estantelivro',
            name='manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estantelivro',
            name='notas_pessoais',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='estantelivro',
            name='numero_paginas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estantelivro',
            name='ultima_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='estantelivro',
            name='capa',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='estantelivro',
            name='data_lancamento',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='estantelivro',
            name='livro_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estantelivro',
            name='sinopse',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='estantelivro',
            unique_together={('usuario', 'livro_id', 'tipo')},
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
