# Generated by Django 5.1 on 2024-11-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contato_delete_cadastro'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoYouTube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='livro',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livro',
            name='mais_vendido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contato',
            name='assunto',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contato',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
