# Generated by Django 5.1 on 2024-11-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_urlexterna_videoyoutube_livro_destaque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlexterna',
            name='imagem',
            field=models.ImageField(default='imagens/default.jpg', upload_to='imagens/'),
        ),
        migrations.AddField(
            model_name='videoyoutube',
            name='imagem',
            field=models.URLField(default='https://example.com/default_image.jpg'),
            preserve_default=False,
        ),
    ]
