# Generated by Django 5.1.1 on 2024-12-20 10:23

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('core', '0008_livrorecomendado_userpreferences'), ('core', '0009_rename_downloads_livro_visualizacoes'), ('core', '0010_remove_userpreferences_usuario_newlivrocache_and_more')]

    dependencies = [
        ('core', '0007_estantelivro_classificacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='downloads',
            new_name='visualizacoes',
        ),
        migrations.CreateModel(
            name='NewLivroCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=200, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('editora', models.CharField(blank=True, max_length=200, null=True)),
                ('data_publicacao', models.CharField(blank=True, max_length=50, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_paginas', models.CharField(blank=True, max_length=50, null=True)),
                ('categoria', models.CharField(blank=True, max_length=200, null=True)),
                ('idioma', models.CharField(blank=True, max_length=50, null=True)),
                ('imagem_url', models.URLField(blank=True, null=True)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_cache', models.DateTimeField(auto_now=True)),
                ('dados_json', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cache de Livro',
                'verbose_name_plural': 'Cache de Livros',
                'indexes': [models.Index(fields=['book_id', 'data_cache'], name='core_newliv_book_id_7c7ec9_idx')],
            },
        ),
        migrations.CreateModel(
            name='NewLivroRecomendado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livro_id', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('1.0'), max_digits=5)),
                ('data_recomendacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', 'titulo'],
                'unique_together': {('usuario', 'livro_id')},
            },
        ),
        migrations.CreateModel(
            name='NewUserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorias_favoritas', models.JSONField(default=dict)),
                ('autores_favoritos', models.JSONField(default=dict)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
