# Generated by Django 5.1.1 on 2024-12-09 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_livrorecomendado_userpreferences'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='downloads',
            new_name='visualizacoes',
        ),
    ]
