# Generated by Django 5.1.1 on 2024-12-20 10:24

from django.db import migrations


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# core.migrations.0011_populate_livro_cache

class Migration(migrations.Migration):

    replaces = [('core', '0011_populate_livro_cache'), ('core', '0012_alter_newlivrorecomendado_options_and_more')]

    dependencies = [
        ('core', '0010_remove_userpreferences_usuario_newlivrocache_and_more'),
    ]

    operations = [
        migrations.RunPython(
            code=core.migrations.0011_populate_livro_cache.populate_cache,
            reverse_code=core.migrations.0011_populate_livro_cache.reverse_populate,
        ),
        migrations.AlterModelOptions(
            name='newlivrorecomendado',
            options={'ordering': ['-score', 'titulo'], 'verbose_name': 'Livro Recomendado', 'verbose_name_plural': 'Livros Recomendados'},
        ),
        migrations.AlterModelOptions(
            name='newuserpreferences',
            options={'verbose_name': 'Preferência do Usuário', 'verbose_name_plural': 'Preferências dos Usuários'},
        ),
        migrations.AlterUniqueTogether(
            name='newlivrorecomendado',
            unique_together=set(),
        ),
    ]
