# Generated by Django 5.1.1 on 2024-12-19 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_populate_livro_cache'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newlivrorecomendado',
            options={'ordering': ['-score', 'titulo'], 'verbose_name': 'Livro Recomendado', 'verbose_name_plural': 'Livros Recomendados'},
        ),
        migrations.AlterModelOptions(
            name='newuserpreferences',
            options={'verbose_name': 'Preferência do Usuário', 'verbose_name_plural': 'Preferências dos Usuários'},
        ),
        migrations.AlterUniqueTogether(
            name='newlivrorecomendado',
            unique_together=set(),
        ),
    ]
