# Generated by Django 5.1.1 on 2024-12-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0013_alter_model_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricoAtividade',
            new_name='ActivityHistory',
        ),
        migrations.RenameModel(
            old_name='Livro',
            new_name='Book',
        ),
        migrations.RenameModel(
            old_name='LivroCache',
            new_name='BookCache',
        ),
        migrations.RenameModel(
            old_name='EstanteLivro',
            new_name='BookShelf',
        ),
        migrations.RenameModel(
            old_name='Contato',
            new_name='Contact',
        ),
        migrations.RenameModel(
            old_name='URLExterna',
            new_name='ExternalURL',
        ),
        migrations.RenameModel(
            old_name='VideoYouTube',
            new_name='YouTubeVideo',
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-data'], 'verbose_name': 'Contato', 'verbose_name_plural': 'Contatos'},
        ),
        migrations.AlterModelOptions(
            name='externalurl',
            options={'verbose_name': 'URL Externa', 'verbose_name_plural': 'URLs Externas'},
        ),
        migrations.AlterModelOptions(
            name='youtubevideo',
            options={'verbose_name': 'Vídeo do YouTube', 'verbose_name_plural': 'Vídeos do YouTube'},
        ),
        migrations.AlterUniqueTogether(
            name='newlivrorecomendado',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='core_users', related_query_name='core_user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='core_users', related_query_name='core_user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterModelTable(
            name='activityhistory',
            table='core_historicoatividade',
        ),
        migrations.AlterModelTable(
            name='book',
            table='core_livro',
        ),
        migrations.AlterModelTable(
            name='bookcache',
            table='core_livrocache',
        ),
        migrations.AlterModelTable(
            name='bookshelf',
            table='core_estantelivro',
        ),
        migrations.AlterModelTable(
            name='contact',
            table='core_contato',
        ),
        migrations.AlterModelTable(
            name='externalurl',
            table='core_urlexterna',
        ),
        migrations.AlterModelTable(
            name='youtubevideo',
            table='core_videoyoutube',
        ),
    ]
