# Generated by Django 5.1.1 on 2024-12-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_historicoatividade_activityhistory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externalurl',
            options={'ordering': ['ordem', 'nome'], 'verbose_name': 'URL Externa', 'verbose_name_plural': 'URLs Externas'},
        ),
        migrations.AlterModelOptions(
            name='youtubevideo',
            options={'ordering': ['ordem', 'titulo'], 'verbose_name': 'Vídeo do YouTube', 'verbose_name_plural': 'Vídeos do YouTube'},
        ),
        migrations.AddField(
            model_name='externalurl',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='externalurl',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='externalurl',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='urls/'),
        ),
        migrations.AlterModelTable(
            name='externalurl',
            table=None,
        ),
        migrations.AlterModelTable(
            name='youtubevideo',
            table=None,
        ),
    ]
