# Generated by Django 5.1.1 on 2024-12-09 19:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livro', models.CharField(max_length=500)),
                ('visualizacoes', models.IntegerField(default=0)),
                ('compartilhamentos_facebook', models.IntegerField(default=0)),
                ('compartilhamentos_twitter', models.IntegerField(default=0)),
                ('compartilhamentos_whatsapp', models.IntegerField(default=0)),
                ('adicoes_estante', models.IntegerField(default=0)),
                ('data', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SiteAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('visitas_total', models.IntegerField(default=0)),
                ('visitas_anonimas', models.IntegerField(default=0)),
                ('visitas_autenticadas', models.IntegerField(default=0)),
                ('usuarios_ativos', models.IntegerField(default=0)),
                ('novos_usuarios', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Análise do Site',
                'verbose_name_plural': 'Análises do Site',
                'get_latest_by': 'data',
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tipo_erro', models.CharField(max_length=100)),
                ('mensagem', models.TextField()),
                ('traceback', models.TextField(null=True)),
                ('url', models.CharField(max_length=500)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sessao_id', models.CharField(max_length=100)),
                ('dispositivo', models.CharField(max_length=50)),
                ('navegador', models.CharField(max_length=50)),
                ('tempo_na_pagina', models.DurationField(null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tipo_relatorio', models.CharField(max_length=50)),
                ('formato', models.CharField(choices=[('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON')], max_length=10)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fim', models.DateField()),
                ('arquivo', models.FileField(upload_to='reports/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SearchAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo_busca', models.CharField(max_length=200)),
                ('tipo_busca', models.CharField(max_length=50)),
                ('resultados_encontrados', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('foi_bem_sucedida', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=50)),
                ('detalhes', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('secao_atual', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
