# Generated by Django 5.1.1 on 2024-12-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_enabled', models.BooleanField(default=True)),
                ('data_retention', models.IntegerField(default=90)),
                ('daily_report', models.BooleanField(default=False)),
                ('alert_threshold', models.IntegerField(default=100)),
                ('notification_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('last_cleanup', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do Analytics',
                'verbose_name_plural': 'Configurações do Analytics',
            },
        ),
    ]
