# Generated by Django 5.1.1 on 2024-12-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_analyticssettings'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookanalytics',
            unique_together={('livro', 'data')},
        ),
        migrations.AddIndex(
            model_name='bookanalytics',
            index=models.Index(fields=['livro', 'data'], name='analytics_b_livro_bbcefd_idx'),
        ),
    ]
