# Generated by Django 5.1.1 on 2024-12-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_bookanalytics_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticssettings',
            name='active_user_period',
            field=models.IntegerField(default=24, help_text='Período em horas para considerar um usuário como ativo'),
        ),
    ]
